services:
  frontend:
    build:
      context: ./ # Assuming this is your frontend directory
    # ports:
    #   - "6000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - scient-network

  backend:
    build:
      context: ./server # Adjust this path to your backend directory
    # ports:
    #   - "6000:6000"
    environment:
      - PORT=3001
      - MONGO_URI=mongo://admin:password@db:27017/scient?authSource=admin
      - JWT_SECRET=sec
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - scient-network

  db:
    image: mongo:8.0.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - db-data:/data/db
    networks:
      - scient-network

  db-client:
    image: mongo-express:1.0.2-20-alpine3.19
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@db:27017/scient?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_SITE_BASEURL: /db-client/
    depends_on:
      - db
    networks:
      - scient-network

networks:
  scient-network:

volumes:
  db-data:
